- name: install prerequisites
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
    # These are MariaDB in Debian, and Oracle's MySQL in Ubuntu
    - default-mysql-server
    - default-mysql-client
    - python-mysqldb # This is needed for ansible

- name: Create database user
  become: true
  mysql_user:
    name: wikiuser
    password: "{{ db_password }}"
    state: present
    priv: "*.*:ALL"
